/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Objetos.Arco;
import Objetos.Nodo;
import Objetos.Plano;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class InterfazPrincipal extends javax.swing.JFrame {

    private JPanelPlano planoOr = new JPanelPlano();
    private JPanelPlano planoRe = new JPanelPlano();

    /**
     * Creates new form InterfazModelo
     */
    public InterfazPrincipal() {

        planoOr.setLocation(0, 0);
        planoOr.setSize(960, 650);

        planoRe.setLocation(0, 0);
        planoRe.setSize(960, 650);

        initComponents();
        this.pnlGrafoOrigen.add(planoOr);
        this.pnlGrafoResidual.add(planoRe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCrearArco = new javax.swing.JButton();
        btnModificarArco = new javax.swing.JButton();
        btnEliminarArco = new javax.swing.JButton();
        btnEliminarNodo = new javax.swing.JButton();
        btnModificarNodo = new javax.swing.JButton();
        btnMoverNodo = new javax.swing.JButton();
        btnCrearNodo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAlg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlGrafoOrigen = new javax.swing.JPanel();
        pnlGrafoResidual = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Algoritmo Ford Fulkerson\n");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(830, 20));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Opciones ARCO");

        btnCrearArco.setBackground(new java.awt.Color(102, 255, 255));
        btnCrearArco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCrearArco.setText("Crear arco");
        btnCrearArco.setBorderPainted(false);
        btnCrearArco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrearArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearArcoActionPerformed(evt);
            }
        });

        btnModificarArco.setBackground(new java.awt.Color(102, 255, 255));
        btnModificarArco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificarArco.setText("Modificar arco");
        btnModificarArco.setBorderPainted(false);
        btnModificarArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarArcoActionPerformed(evt);
            }
        });

        btnEliminarArco.setBackground(new java.awt.Color(102, 255, 255));
        btnEliminarArco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminarArco.setText("Eliminar arco");
        btnEliminarArco.setBorderPainted(false);
        btnEliminarArco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarArcoActionPerformed(evt);
            }
        });

        btnEliminarNodo.setBackground(new java.awt.Color(102, 255, 255));
        btnEliminarNodo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminarNodo.setText("Eliminar nodo");
        btnEliminarNodo.setBorderPainted(false);
        btnEliminarNodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarNodoActionPerformed(evt);
            }
        });

        btnModificarNodo.setBackground(new java.awt.Color(102, 255, 255));
        btnModificarNodo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificarNodo.setText("Modificar nodo");
        btnModificarNodo.setBorderPainted(false);
        btnModificarNodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarNodoActionPerformed(evt);
            }
        });

        btnMoverNodo.setBackground(new java.awt.Color(102, 255, 255));
        btnMoverNodo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMoverNodo.setText("Mover nodo");
        btnMoverNodo.setBorderPainted(false);
        btnMoverNodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMoverNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverNodoActionPerformed(evt);
            }
        });

        btnCrearNodo.setBackground(new java.awt.Color(102, 255, 255));
        btnCrearNodo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCrearNodo.setText("Crear nodo");
        btnCrearNodo.setBorderPainted(false);
        btnCrearNodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrearNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearNodoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Opciones NODO");

        btnAlg.setBackground(new java.awt.Color(102, 255, 255));
        btnAlg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlg.setText("Alg FLUJO MAX");
        btnAlg.setBorderPainted(false);
        btnAlg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlgActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Opciones Ford Fk");

        javax.swing.GroupLayout pnlGrafoOrigenLayout = new javax.swing.GroupLayout(pnlGrafoOrigen);
        pnlGrafoOrigen.setLayout(pnlGrafoOrigenLayout);
        pnlGrafoOrigenLayout.setHorizontalGroup(
            pnlGrafoOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        pnlGrafoOrigenLayout.setVerticalGroup(
            pnlGrafoOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Grafo Origen", pnlGrafoOrigen);

        javax.swing.GroupLayout pnlGrafoResidualLayout = new javax.swing.GroupLayout(pnlGrafoResidual);
        pnlGrafoResidual.setLayout(pnlGrafoResidualLayout);
        pnlGrafoResidualLayout.setHorizontalGroup(
            pnlGrafoResidualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        pnlGrafoResidualLayout.setVerticalGroup(
            pnlGrafoResidualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Grafo Residual", pnlGrafoResidual);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarArco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarArco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearArco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarNodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarNodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMoverNodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearNodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(btnAlg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCrearNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoverNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnCrearArco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarArco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarArco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnAlg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Archivo");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Deshacer");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nuevo Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Abrir Archivo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Guardar Archivo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearNodoActionPerformed
        planoOr.accionBoton(1);
    }//GEN-LAST:event_btnCrearNodoActionPerformed

    private void btnEliminarNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarNodoActionPerformed
        planoOr.accionBoton(5);
    }//GEN-LAST:event_btnEliminarNodoActionPerformed

    private void btnMoverNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverNodoActionPerformed
        planoOr.accionBoton(3);
    }//GEN-LAST:event_btnMoverNodoActionPerformed

    private void btnCrearArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearArcoActionPerformed
        planoOr.accionBoton(2);
    }//GEN-LAST:event_btnCrearArcoActionPerformed

    private void btnModificarNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarNodoActionPerformed
        planoOr.accionBoton(4);
    }//GEN-LAST:event_btnModificarNodoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        InterfazPrincipal nuevaI = new InterfazPrincipal();
        nuevaI.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        JFileChooser seleccionar = new JFileChooser();
        File archivo;

        if (seleccionar.showDialog(null, "Abriendo Archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();

            if (archivo.getName().endsWith("txt")) {

                String linea, partes[];
                Plano plano = new Plano();

                try {

                    FileReader fr = new FileReader(archivo.getAbsolutePath());
                    BufferedReader br = new BufferedReader(fr);

                    while ((linea = br.readLine()) != null) {
                        partes = linea.split(";");

                        if (partes[0].equalsIgnoreCase("Nodo")) {

                            int id = Integer.parseInt(partes[1]);
                            int tipo = Integer.parseInt(partes[2]);
                            int posx = Integer.parseInt(partes[3]);
                            int posy = Integer.parseInt(partes[4]);

                            Nodo nodo = new Nodo(id, tipo, posx, posy);
                            plano.adicionarNodo(nodo);
                        } else {
                            int id = Integer.parseInt(partes[1]);
                            int peso = Integer.parseInt(partes[2]);
                            int nodoOrigen = Integer.parseInt(partes[3]);
                            int nodoDestino = Integer.parseInt(partes[4]);

                            Arco arco = new Arco(id, peso, nodoOrigen, nodoDestino);
                            plano.adicionarArco(arco);
                        }
                    }

                } catch (IOException e) {
                    System.out.println(e);
                }

                planoOr.setPlano(plano);

            } else {
                JOptionPane.showMessageDialog(this, "Archivo no valido");
            }
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        JFileChooser seleccionar = new JFileChooser();
        File archivo;

        if (seleccionar.showDialog(null, "Guardando archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();

            if (archivo.getName().endsWith("txt")) {

                String line;
                try {
                    FileWriter fichero = new FileWriter(archivo);

                    for (Nodo nodo : planoOr.getPlano().getNodos()) {
                        line = "Nodo;" + nodo.getId() + ";" + nodo.getTipo()
                                + ";" + nodo.getX() + ";" + nodo.getY() + "\n";
                        fichero.write(line);
                    }

                    for (Arco arco : planoOr.getPlano().getArcos()) {
                        line = "Arco;" + arco.getId() + ";" + arco.getPeso() + ";"
                                + arco.getNodoOrigen() + ";" + arco.getNodoDestino() + "\n";
                        fichero.write(line);
                    }

                    fichero.close();

                } catch (IOException e) {
                    System.out.println(e);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Archivo no valido");
            }
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnModificarArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarArcoActionPerformed
        planoOr.accionBoton(6);
    }//GEN-LAST:event_btnModificarArcoActionPerformed

    private void btnEliminarArcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarArcoActionPerformed
        planoOr.accionBoton(7);
    }//GEN-LAST:event_btnEliminarArcoActionPerformed

    private void btnAlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlgActionPerformed
        // TODO add your handling code here:
        try {
            planoRe.setPlano(planoOr.algoritmo());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese un grafo...");
        }
    }//GEN-LAST:event_btnAlgActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        planoOr.deshacer();
    }//GEN-LAST:event_jMenuItem5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlg;
    private javax.swing.JButton btnCrearArco;
    private javax.swing.JButton btnCrearNodo;
    private javax.swing.JButton btnEliminarArco;
    private javax.swing.JButton btnEliminarNodo;
    private javax.swing.JButton btnModificarArco;
    private javax.swing.JButton btnModificarNodo;
    private javax.swing.JButton btnMoverNodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlGrafoOrigen;
    private javax.swing.JPanel pnlGrafoResidual;
    // End of variables declaration//GEN-END:variables
}
